### ISSUE TITLE
Add script for generating / fetching test data set and reference genome

### ISSUE THREAD

**Issue by danielecook** [AndersenLab/wi-gatk#5]

**Comment by danrlu** [comment]
When I was running wi-nf on Quest, all the ftp step failed to fetch and I couldn't figure out how to fix it. The fetch would work if running on terminal, but would fail when called within the pipeline. It may be a Quest setting issue, but it's probably more robust to download files outside of the workflow, and use the local files.

**Comment by danielecook** [comment]
@danrlu there are a couple of things you an try. Quest has weird networking issues.

1.) Try swapping `ftp` for `http` in the URL.
2.) Try using `curl` instead of `wget` or use wget with the `-L` option.
3.) If all else fails download locally and upload...the files are not that big.

Once you have this setup please close this issue as I have added the script to `scripts/setup_genome.sh`. Thanks!
